name: deep6
description:

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.1.6+13

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.2.5
  firebase_analytics: ^1.0.4
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  audioplayers: ^0.7.8
  intl: ^0.15.7
  quiver: ^2.0.0
  flutter_local_notifications: ^0.4.2
  shared_preferences: ^0.4.3
  screen: ^0.0.4
  launch_review: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/sounds/click.mp3
  - assets/sounds/background.mp3

  - assets/json/de/prologue.json
  - assets/json/de/chapter_1.json
  - assets/json/de/chapter_2.json
  - assets/json/de/chapter_3.json
  - assets/json/de/chapter_4.json
  - assets/json/de/chapter_5.json
  - assets/json/de/chapter_6.json
  - assets/json/de/chapter_7.json
  - assets/json/de/chapter_8.json
  - assets/json/de/chapter_9.json
  - assets/json/de/chapter_10.json
  - assets/json/de/chapter_11.json
  - assets/json/de/chapter_12.json
  - assets/json/de/chapter_13.json
  - assets/json/de/chapter_14.json
  - assets/json/de/profile_details.json
  - assets/json/de/epilogue.json
  - assets/json/de/rateus.json

  - assets/json/en/prologue.json
  - assets/json/en/chapter_1.json
  - assets/json/en/chapter_2.json
  - assets/json/en/chapter_3.json
  - assets/json/en/chapter_4.json
  - assets/json/en/chapter_5.json
  - assets/json/en/chapter_6.json
  - assets/json/en/chapter_7.json
  - assets/json/en/chapter_8.json
  - assets/json/en/chapter_9.json
  - assets/json/en/chapter_10.json
  - assets/json/en/chapter_11.json
  - assets/json/en/chapter_12.json
  - assets/json/en/chapter_13.json
  - assets/json/en/chapter_14.json
  - assets/json/en/profile_details.json
  - assets/json/en/epilogue.json
  - assets/json/en/rateus.json

  - assets/images/splash_screen.png
  - assets/images/profile_cure.png
  - assets/images/profile_orlow.png
  - assets/images/profile_mueller.png
  - assets/images/comm_blue.png
  - assets/images/comm_red.png
  - assets/images/app_icon.png
  - assets/images/launcher_icon_droid.png
  - assets/images/launcher_icon_ios.png
  - assets/images/bg_main.png
  - assets/images/bg_ch_1_4.png
  - assets/images/bg_ch_5_7.png
  - assets/images/bg_ch_8_9.png
  - assets/images/bg_ch_10_11.png
  - assets/images/bg_ch_12_13.png
  - assets/images/bg_ch_14.png
  - assets/images/notification.png
  - assets/images/fingerprint.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
